language: node_js

node_js: stable

cache: yarn

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

script:
  - set -e
  - yarn lint
  - yarn build
  - yarn run build-storybook

deploy:
  - provider: script
    script: standard-version && git push --follow-tags origin release && cd dist && npm publish --access=public
    on:
      branch: release
  - provider: pages
    email: admin@1stg.me
    name: JounQin
    skip_cleanup: true
    github_token: $GH_TOKEN
    keep_history: true
    allow_empty_commit: false
    local_dir: storybook-static
    on:
      branch: master
